print("hello")

In [1]:
print("Hello, Jupyter!")

Hello, Jupyter!


pip install numby

In [ ]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Data1:", data1)
print("Data2:\n", data2)
new_data = data2.reshape(3, 2)
print("Reshaped Data2:\n", new_data)

Data1: [1 2 3 4 5]
Data2:
 [[1 2 3]
 [4 5 6]]
Reshaped Data2:
 [[1 2]
 [3 4]
 [5 6]]


In [8]:
print(data2.shape)
print(data1.ndim)
print(data2.dtype)
print(data2.size)
print(data2.itemsize)
print(data2.max())
print(data2.min())
print(data2.sum())


(2, 3)
1
int64
6
8
6
1
21


In [ ]:
for x in data1:
    print(x)

NameError: name 'data1' is not defined